specfile_path: libxcrypt.spec

files_to_sync:
  - libxcrypt.spec
  - .packit.yaml

upstream_package_name: libxcrypt
upstream_project_url: https://github.com/besser82/libxcrypt
upstream_tag_template: v{version}
downstream_package_name: libxcrypt
dist_git_namespace: rpms
create_pr: True

actions:
  post-upstream-clone: "wget https://src.fedoraproject.org/rpms/libxcrypt/raw/main/f/libxcrypt.spec -O libxcrypt.spec"
  post-modifications: "sed -i -e 's!%bcond_with    bootstrap!%bcond_without bootstrap!g' -e 's!^Patch!#&!g' libxcrypt.spec"

jobs:
- job: upstream_koji_build
  trigger: commit
  metadata:
    branch: develop
    scratch: true
    targets: fedora-all

- job: upstream_koji_build
  trigger: pull_request
  metadata:
    scratch: true
    targets: fedora-all

- job: propose_downstream
  trigger: release
