#! /bin/bash

set +x
set +e

echo -e '\033[33;1m::: ENVIRONMENT\033[0m'
printenv | sort
echo

echo -e '\033[33;1m::: HOMEDIR\033[0m'
echo $HOME
ls -l $HOME
if [ -d $HOME/.local ]; then
  echo
  echo $HOME/.local
  ls -l $HOME/.local
fi
if [ -d $HOME/.local/bin ]; then
  echo
  echo $HOME/.local/bin
  ls -l $HOME/.local/bin
fi
if [ -d $HOME/bin ]; then
  echo
  echo $HOME/bin
  ls -l $HOME/bin
fi
echo

echo -e '\033[33;1m::: WORKDIR\033[0m'
pwd
ls -l
echo

echo -e '\033[33;1m::: TOOLS\033[0m'
goodpy=
for py in python3 python3.5 python3.6 python3.7 python3.8; do
  command -V $py || continue
  $py --version 2>&1 || continue
  if $py -c 'import venv'; then
    goodpy=$py
    echo "$py: venv available"
  else
    echo "$py: venv not available"
  fi
done
command -V ninja    && ninja --version   2>&1

echo -e '\033[33;1m::: VENV TEST\033[0m'
set -ex
$goodpy -m venv --system-site-packages --clear build_venv
. build_venv/bin/activate
command -V python
python --version
python -m pip install codecov meson
command -V meson
meson --version

exit 0
