#! /usr/bin/python3
#
#   Copyright 2017, 2018, 2019 Zack Weinberg
#
#   This library is free software; you can redistribute it and/or
#    modify it under the terms of the GNU Lesser General Public License
#   as published by the Free Software Foundation; either version 2.1 of
#   the License, or (at your option) any later version.
#
#   This library is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Lesser General Public License for more details.
#
#   You should have received a copy of the GNU Lesser General Public
#   License along with this library; if not, see
#   <https://www.gnu.org/licenses/>.

"""Install a symbolic link.  Expects MESON_INSTALL_DESTDIR_PREFIX to
be set in the environment; a symlink from ${link_name} to ${target}
will be created in ${MESON_INSTALL_DESTDIR_PREFIX}/${subdir}.
If that directory does not exist, it is created.
No check is made for whether ${target} exists.
"""

import argparse
import os


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("subdir",
                    help="Directory (below MESON_INSTALL_DESTDIR_PREFIX)"
                    " in which to create the symlink.")
    ap.add_argument("target", help="Target of the symlink.")
    ap.add_argument("link_name", help="Name of the link to create.")
    args = ap.parse_args()

    link_path = os.path.join(os.environ["MESON_INSTALL_DESTDIR_PREFIX"],
                             args.subdir, args.link_name)
    link_dir, link_name = os.path.split(link_path)
    os.makedirs(link_dir, exist_ok=True)
    os.chdir(link_dir)
    os.symlink(args.target, link_name)


main()
